### ISSUE TITLE
툴팁 표시 오류 문의

### ISSUE THREAD

**Issue by cad627** [nhnent/tui.chart#1]
그래프를 두개 그릴 경우, 두번째 그래프의 툴팁이 표시되지 않습니다. 
정확히는 첫번째 그래프 툴팁이 표시되는 것으로 같습니다.

라인차트를 두개 그리는데 첫번째 그래프엔 데이터가 하나고, 두번째 그래프에 여러개인 경우,
두번째 그래프의 첫 데이터만 툴팁이 위쪽 그래프에 나타납니다.

툴팁을 그래프들이 공유하는 것으로 보입니다.
확인 부탁드리겠습니다^^

**Comment by extremeFE** [comment]
차트 이용에 감사드립니다.

금일(2015년 10월 29일) 정기배포가 이루어질 예정입니다.
이번 버전에서는 해당 오류가 수정되어 배포됩니다.

감사합니다.

**Comment by extremeFE** [comment]
배포가 완료되었습니다.

이번에 tui.chart로  네임스페이스가 변경되었습니다.

bower를 사용하실 경우에는 튜토리얼에 따라 변경된 내용을 적용해 사용하시기 바랍니다.
튜토리얼 : https://github.com/nhnent/tui.chart/wiki/tutorial

samples를 사용하시는 경우라면 samples에 포함된 라이브러리까지 모두 교체하여 사용하셔야 합니다.

다시한번 차트 이용에 감사드립니다.

**Comment by cad627** [comment]
감사합니다
