### ISSUE TITLE
tooltip 템플릿 사용시 한글 텍스트에 대해 줄바뀜 현상

### ISSUE THREAD

**Issue by godori** [nhnent/tui.chart#10]
안녕하세요 
툴팁 표시 관련하여 문의드립니다.
툴팁 옵션에 템플릿 적용시 추가적인 텍스트를 넣으면 한글만 줄바뀜 문제가 발생합니다.

다음 두 이미지와 같이 value값 다음에 숫자, 특수문자(%,! 등...), 영문자는 
value값과 함께 한 줄로 처리가 되지만 한글만 줄이 바뀌어서 처리가 됩니다.
![image](https://cloud.githubusercontent.com/assets/8243284/24032158/d9480034-0b29-11e7-95a9-a3ef927c2502.png)
![image](https://cloud.githubusercontent.com/assets/8243284/24032164/ded506d2-0b29-11e7-9042-b9699ad65f20.png)

템플릿은 다음과 같은 방식으로 사용하고 있습니다.
```javascript
tooltip : {
  offsetY: -40,
    offsetX: -5,
      template: function(category, item) {
        var html =  '<time class="date">'+category+'</time>'
              + '<strong class="count">'+item.value+'회'+'</strong>'
        return html;
      }
},
```
값과 단위를 붙여서 표기를 하고 싶은데, 방법이 없는지요?

**Comment by junghwan-park** [comment]
안녕하세요 

문의 주신 내용을 확인해 보니 tooltip template 적용시 내부에 한글이 포함되면 해당 한글 단어가 줄바뀜 되는 현상이 발생하는 것을 확인했습니다.

이 현상은 한글을 포함한 엘리먼트의 부모 엘리먼트 너비가 고정너비로 지정되지 않은 상태에서만 발생하는 것으로 보이는데요,
다음과 같이 wrapper 엘리먼트로 한번 감싸주고 그 wrapper에 'auto'가 아닌 고정 width를 주면 텍스트의 길이가 width보다 작은 한 한글로 된 단위도 값에 붙여서 표기가 됨을 확인 할 수 있습니다.

예제는 다음과 같습니다.

``` javascript
template: function(category, item) {
    var html =  '<div style="width:100px"><time class="date">' + category + '</time>'
        + '<strong class="count">' + item.value + '회' + '</strong></div>'

    return html;
}
```

**Comment by godori** [comment]
우선 답변 감사합니다!

횟수에 따라 툴팁 크기가 달라져야 해서 
가능한 고정 크기를 주지 않으려 하였는데요,
글자 수에 따라 width를 바꿈으로써 해결했습니다.

한글은 왜 안되는 걸까요... 🤔
