### ISSUE TITLE
legend 표시하지 않을 경우 category 오른쪽 텍스트가 잘려 보입니다.

### ISSUE THREAD

**Issue by godori** [nhnent/tui.chart#11]
안녕하세요
legend의 옵션을 visible : false로  변경하였을 때, 
오른쪽 끝의 카테고리 텍스트가 잘려서 나오게 되는 이슈가 있습니다.
legend를 사용하지 않는 그래프의 카테고리에 대해 약간의 공간이 있으면 좋을 것 같은데,
혹시 다른 해결 가능한 방법이 있을지요?

```javascript
legend: {
	visible: false,
	showCheckbox: false,
},
```
![image](https://cloud.githubusercontent.com/assets/8243284/24036014/3042681e-0b3b-11e7-8ca1-3f9f9b6c8155.png)

**Comment by junghwan-park** [comment]
안녕하세요

legend가 없는 상태의 chart의 우측 여백확보가 고려 되지 않았네요.
추후 개선 목록에 추가해서 차트 영역을 조정하겠습니다. 

감사합니다. :)

**Comment by godori** [comment]
@junghwan-park 확인 감사드립니다!
