### ISSUE TITLE
TOAST chart 사용 시 문의 드립니다.

### ISSUE THREAD

**Issue by niceliberty** [nhnent/tui.chart#111]
TOAST chart 사용 시 문의 드립니다.

http://210.115.36.146:8099/integrateDB/chart/examples/subpopulation.jsp

위 싸이트 처럼 bar chart를 만들었습니다.

원하는 기능은 위 chart에서 bar를 클릭 하면 브라우저 오른 편에 pie chart를

나오게 하고 싶습니다.

즉, bar 클릭 시 왼쪽 frame으로 url 링크 입니다.

click event를 못 찾겠습니다.

도움 부탁 드립니다.

**Comment by jinwoo-kim-nhn** [comment]
##The examples and documentation below will help. Thank you.
- https://github.com/nhnent/tui.chart/blob/production/docs/wiki/features-series.md

```js
var chart = tui.chart.columnChart(container, data, options);
 chart.on('selectSeries', function(data) {
     console.log('kkk', data);
 });

```
