### ISSUE TITLE
[Question] Is there an option to hide both axes?

### ISSUE THREAD

**Issue by CSADn** [nhnent/tui.chart#112]
I wan't able to figure out how to hide both axes.
Is it possible?
Thank you.

**Comment by jinwoo-kim-nhn** [comment]
- For line-type charts, you can hide the y-axis in the following ways, but there is no way at other chart , and there is no official way to hide the x-axis.
We will seriously consider the options to solve this.

```js
var options = {
    ...
    yAxis: {
        pointOnColumn: false,
        showLabel: false
    },
    ...
}
```
