### ISSUE TITLE
라인 차트에서 굵기를 조절, Y축 값을 안 보이게 할 수 있을까요?

### ISSUE THREAD

**Issue by GangHyeok-Ji** [nhnent/tui.chart#113]
좋은 차트를 만들어 주셔서 감사드립니다!

## Version
3.1.1

## Development Environment
Chrome, IE, Windows 10

## Current Behavior
다음과 같은 라인 차트를 사용하는데  두 라인중 한 라인을 얇게 만들고 싶습니다. 
그리고 왼쪽에 Y축 값을 숨겨서 그래프를 넓게 보이게 하고 싶습니다.
![image](https://user-images.githubusercontent.com/31868822/42482857-fe90afce-8424-11e8-8e15-bc202eea89a4.png)

```

## Expected Behavior
두 라인중 한 라인을 얇게 만들고 싶습니다.
Y값 값을 숨기고 싶습니다.

**Comment by jinwoo-kim-nhn** [comment]
1. For line chart, you can hide the y axis by setting the value of yAxis.pointOnColumn, yAxis.showLabel option to false as shown below.

```js
var options = {
    ...
    yAxis: {
        pointOnColumn: false,
        showLabel: false
    },
    ...
}
```

2. Can control the thickness of lines by giving series.pointWidth option as below, but there is no way to change the line weight of specific series group to different.

```js
var options = {
    ...
    series: {
        pointWidth: 1
    },
    ...
}
```

**Comment by GangHyeok-Ji** [comment]
빠르게 답변 해주셔서 감사합니다.
