### ISSUE TITLE
안녕하세요 tui.chart 사용 관련해서 질문드립니다.

### ISSUE THREAD

**Issue by warpgate3** [nhnent/tui.chart#115]
먼저 이렇게 훌륭한 차트를 제공해주셔서 감사합니다^^

차트를 사용해볼려고 하는데 차트에 바인딩된 json 데이트를 변경하면
해당 데이터 값을 차트에 반영할수 있는 방법이 있을까요?

var data = [1, 2]
data.push(3);
chart.rebuild() // <--- 이런 느낌의

감사합니다.

## Current Behavior

```js
// Write example code
```

**Comment by jinwoo-kim-nhn** [comment]
hello @warpgate3 
You can use the rerender api as shown in the example below.

I admit that it is currently included in the [api document](https://nhnent.github.io/tui.chart/latest/AreaChart.html#rerender) but is not useful.

It should be noted that the structure of the data for the initial creation and the data for the rerender is slightly different to note is that.

A little inconvenient, but the data for the current "rerender" should be wrapped in a chartType.


```js
var container = document.getElementById('chart-area');
var data = {
    categories: ['Category1', 'Category2', 'Category3', 'Category4'],
    series: [{
        name: 'Series1',
        data: [0, 0, 0]
    }, {
        name: 'Series2',
        data: [0, 0, 0]
    }, {
        name: 'Series3',
        data: [0, 0, 0]
    }]
};
var options = {
    chart: {
        width: 700,
        height: 400
    }
};

var chart = tui.chart.areaChart(container, data, options);

setInterval(function () {
    chart.rerender({area: [true, true, true]}, {
        categories: ['01/01/2016', '02/01/2016', '03/01/2016', '04/01/2016'],
        series: {
            area: [{
                name: 'Series1',
                data: [10, 10, 10]
            }, {
                name: 'Series2',
                data: [10, 10, 10]
            }, {
                name: 'Series3',
                data: [10, 10, 10]
            }]
        }
    });
}, 1000);

```

**Comment by warpgate3** [comment]
thanx 👍
