### ISSUE TITLE
Webpack + Babel-polyfill: "only one instance of babel-polyfill is allowed", cannot load module

### ISSUE THREAD

**Issue by GitSquared** [nhnent/tui.chart#119]
I'm trying to use tui-chart on a webpack project in which i use `babel-polyfill`.

## Version
tui-chart v3.2.1 (from NPM)

## Development Environment
Webpack 4, babel-polyfill 6.26

## Current Behavior
When importing tui-chart, it throws an error stating that "only one instance of babel-polyfill is allowed". **Manually editing the source to bypass this check makes everything works flawlessly**, so i'm wondering why it's there.

```js
// webpack-config.js
module.exports = {
    entry: ["babel-polyfill", "./webapp/index.js"],
    mode: "development",
    module: {
        rules: [
            { test: /\.js$/, exclude: /node_modules/, loader: "babel-loader" }
        ]
    },
    ...
};
```

```js
// webapp/index.js
import "babel-polyfill";
import chart from "tui-chart";

// Console error throwed: "only one instance of babel-polyfill is allowed".
```

```js
// tui-chart.js line 83
    if (global._babelPolyfill) {
>	  throw new Error("only one instance of babel-polyfill is allowed");
	}
	global._babelPolyfill = true;
```

## Expected Behavior
tui-chart gets loaded without throwing any blocking error.

**Comment by jinwoo-kim-nhn** [comment]
@GitSquared 

'tui chart' has a dependency on 'babel-polyfill', so babel-polyfill exists in the code.
We are aware of this problem and plan to distribute files that do not have 'babel-polyfill' as soon as possible.

thanks

**Comment by jinwoo-kim-nhn** [comment]
@GitSquared 
I corrected and distributed this problem.
See the Release Notes.

thanks

**Comment by GitSquared** [comment]
Awesome!
