### ISSUE TITLE
툴팁의 category값과 Axis에 표시되는 category값을 다르게 표시하고 싶습니다.

### ISSUE THREAD

**Issue by godori** [nhnent/tui.chart#12]
안녕하세요?
공유해주신 차트 소스 감사히 사용하고 있습니다.
혹시 툴팁에 표시되는 category값과 xAxis에 표시되는 category의 값을 다르게 하는 것이 가능할까요?

현재 코드에서 툴팁 옵션의 다음 템플릿을 사용하면 아래 이미지와 같은 결과를 얻을 수 있는데요,

**툴팁 템플릿 옵션**
```javascript
template: function(category, item) {
	var html = '<section class="layerContents">'
			+ '<time class="date">'+category+'</time>'
			+ '<strong class="count">'+item.value+'회'+'</strong>'
		        + '</section></aside>';
	return html;
}
```
**결과**
![image](https://cloud.githubusercontent.com/assets/8243284/25928372/db9160e6-3636-11e7-9328-277a069ee79b.png)

현재 두 값이 똑같지만 툴팁에만 년도가 표시되도록 변경하고 싶어 포맷을 변경해 보았습니다

**xAxis 옵션 변경**
```javascript
getDateFormat = function(){
	if(period === 'recentWeek')
		return 'M.dd';
	else(period === 'recentYear')
		return 'M월';
};
...
var options = { 
   xAxis: {
        type: 'datetime',
        dateFormat: getDateFormat()
   }
}

```
**결과**
![image](https://cloud.githubusercontent.com/assets/8243284/25928926/e90cc460-3639-11e7-9278-bfd4747a1670.png)

위 결과처럼 xAxis의 데이터 포맷을 변경하면 툴팁의 category도 동시에 변경되어 버립니다.

포맷 변경 외에도 beforeShowTooltip 등으로 값을 변경해보려 하였는데, '12월' 등으로 카테고리 값이 먼저 결정되면 추가적인 년도 정보를 툴팁에 표시할 수가 없네요 ㅠ.ㅠ

툴팁 템플릿 변수 중 item 오브젝트에 포맷 변경 전 카테고리 값이 들어가면 가능할 듯도 한데요, 제가 찾지 못한 방법이 있을지 여쭤봅니다.

**Comment by junghwan-park** [comment]
안녕하세요 ~

문의해주신 포멧 변경 전 카테고리 값은 현재로서는 툴팁 템플릿 함수로 전달되지 않고 있습니다.
Axis 옵션의 `dateFormat`을 사용하면 내부에서 관리하는 카테고리 값이 변경되어 template 함수에는 변경된 포멧의 카테고리 값만 전달되고 있습니다.

하지만 부가적인 정보를 더 제공하면 tooltip에 더 풍부한 표현이 가능할 것 이라고 생각합니다.
먼저 포멧 전 상태의 카테고리 값처럼 툴팁 템플릿 함수에 부가적으로 더 제공할 정보들이 있는지 검토한 뒤,
추후 TUI Chart 개선 목록에 포함시키도록 하겠습니다.

감사합니다. =)

**Comment by godori** [comment]
정환님, 검토해주셔서 감사합니다!

**Comment by godori** [comment]
업데이트 예정이 있는지 궁금하네요

**Comment by youjung-hong** [comment]
@godori 차트에 관심가져 주셔서 감사합니다.

해당 이슈 v2.10.1 릴리스에서 해결되었습니다.
`categoryTimestamp`를 통해 timestamp 값이 전달되도록 수정하였으며

자세한 내용은 아래 링크에서 확인하실 수 있습니다.
https://github.com/nhnent/tui.chart/wiki/features-tooltip#setting-template-of-tooltip

감사합니다!
