### ISSUE TITLE
title앞에 이미지를 넣을 수 있을까요?

### ISSUE THREAD

**Issue by GangHyeok-Ji** [nhnent/tui.chart#122]
## Version
3.1.1

## Development Environment
Chrome, Windows 10

## Current Behavior
1. options - chart - title 앞에 이미지를 넣고 싶습니다.
(차트 타이틀 앞에 이미지를 넣을 수 있을까요?)
2. 애니메이션 속도를 조절할 수 있나요?

![title_insert_image](https://user-images.githubusercontent.com/31868822/43429504-bf96dade-949e-11e8-8db1-6cb84e664a7d.png)

## Expected Behavior
1.차트 타이틀 앞쪽에 이미지를 넣을 수 있을까요?
2.애니메이션 속도를 조절하고 싶습니다.

**Comment by jinwoo-kim-nhn** [comment]
@GangHyeok-Ji 
Unfortunately, we do not officially provide a way to do them.
However, it will be positively reflected in the direction of future chart improvement.
thank you.

**Comment by GangHyeok-Ji** [comment]
감사합니다.
