### ISSUE TITLE
lineChart 질문입니다

### ISSUE THREAD

**Issue by ssalangsj** [nhnent/tui.chart#124]
1. plot.lines 에서 Y축으로는 구분선이 있는데
X축으로 구분선을 만들수는없나요?

2. series 값마다 X축 구분선이 가능한가요?

## Current Behavior

```js
// Write example code
```

**Comment by jinwoo-kim-nhn** [comment]
@ssalangsj 
The x-axis Horizon line is not currently supported.
Please refer to the guide below and how to use examples.
* Wiki guide
  - https://github.com/nhnent/tui.chart/blob/production/docs/wiki/features-plot.md
* Example
  - https://nhnent.github.io/tui.chart/latest/tutorial-example04-05-area-chart-merge-overlapping-plotbands.html
