### ISSUE TITLE
o is not a function 에러가 납니다.

### ISSUE THREAD

**Issue by byunghweeLee** [nhnent/tui.chart#128]
실행하면 자꾸 o is not a function 에러가 뜨고요..
chart.min.js에서 
var i=o(t,e.width,e.height),a=i.rect(0,0,e.width,e.height);
이부분에서 에러가 나는데 어떻게 해결해야 하나요?

<%@ page contentType="text/html; charset=utf-8" pageEncoding="utf-8"%>
<!DOCTYPE html>
<html lang="ko">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta http-equiv="keywords" content="키워드" />
		<meta name="description" content="코멘트" />
		<meta name="copyright" content="Copyright. All rights reserved." />
		<title></title>
		<link rel="shortcut icon" type="image/x-icon" href="/common/images/favicon.ico" />
		
		<script type="text/javascript" src="/common/js/jquery-1.12.1.min.js"></script>
		<link rel="stylesheet" href="/common/tui-chart/dist/chart.css" />
		<link rel="stylesheet" href="/common/tui-chart/dist/chart.min.css" />
		<script type='text/javascript' src='https://rawgit.com/nhnent/tui.code-snippet/1.0.8/code-snippet.js'></script>
		<script src="/common/tui-chart/dist/chart.js"></script>
		<script src="/common/tui-chart/dist/chart.min.js"></script>
	<script type="text/javascript">
	$(document).ready(function() {
		
		
				var container = document.getElementById('chart01');
				
				var data = {
					    categories: ['cate1', 'cate2', 'cate3'],
					    series: [
					        {
					            name: 'Legend1',
					            data: [20, 30, 50]
					        },
					        {
					            name: 'Legend2',
					            data: [40, 40, 60]
					        },
					        {
					            name: 'Legend3',
					            data: [60, 50, 10]
					        },
					        {
					            name: 'Legend4',
					            data: [80, 10, 70]
					        }
					    ]
					};
				var options = {
					    chart: {
					        title: 'test',
					        width: 700,
					        height: 3500
					    },
					    yAxis: {
					        title: ''
					    },
					    xAxis: {
					        title: ''
					    }
					};
				tui.chart.barChart(container, data, options);
				$("#chart01").css("height", "100%");
			});
	</script>
	</head>
	
	<body>
	
		<div id="chart01"></div>
	</body>
</html>

**Comment by jinwoo-kim-nhn** [comment]
@byunghweeLee 
It is difficult to reproduce it because you can not know the used version in your `chart.js`.
It is expected to be a problem with certain versions. We recommend using the `latest version`.


You can easily use charts as an example below.
- https://nhnent.github.io/tui.chart/latest/tutorial-example01-01-bar-chart-basic.html#

This is an example of the use of full code.
- https://github.com/nhnent/tui.chart/blob/master/examples/example01-01-bar-chart-basic.html
