### ISSUE TITLE
[Question] xAxis, yAxis 영역을 tooltip처럼 컨트롤 할 수 있을 까요?

### ISSUE THREAD

**Issue by GangHyeok-Ji** [nhnent/tui.chart#129]
좋은 차트를 공개해 주셔서 대단히 감사합니다.

제가 차트에서 tooltip부분을 변경해서 사용하고 있는데요;.

tooltip: {
    	grouped: true,
    	/*suffix: '원', */
    	template: function(category, item) {
    		var wrap = "<div class='tui-chart-default-tooltip'/>";
    		var head = "<div class='tui-chart-tooltip-head show'>" + "&nbsp;" + category +"</div>";
    		var s_style = "";
    		var upDownTxt = "";
    		var thisMounth = Number(item[1].value.replace(",",""));
    		var preMounth = Number(item[0].value.replace(",",""));    		
    		if(preMounth - thisMounth > 0){
    			s_style = "style='color:#ffffff; font-weight: bold; font-size: 11px;'";
    			upDownTxt = "<span style='color:#00A2E8;'>▼</span>";
    		}else if(preMounth - thisMounth < 0){
    			s_style = "style='color:#ffffff; font-weight: bold; font-size: 11px;'";
    			upDownTxt = "<span style='color:#F47378;'>▲</span>";
    		}
    	 	var body = "<div class='tui-chart-tooltip-body'>"
    	 				+ "<div class='tui-chart-legend-rect column' style='background-color:#b4b4b4; display:inline; font-size: 11px;'>&nbsp;&nbsp;&nbsp;&nbsp;</div><div style='display:inline;  font-size: 11px;'>"+" 전월"+"</div><div class='tui-chart-tooltip-value' style='display:inline; font-size: 11px;'>" + numberWithCommas(preMounth) +"원 </div>"
    	 				+ "<br/><div class='tui-chart-legend-rect column' style='background-color:#366d9f; display:inline;  font-size: 11px;'>&nbsp;&nbsp;&nbsp;&nbsp;</div><div style='display:inline;  font-size: 11px;'>"+" 금월"+"</div><div class='tui-chart-tooltip-value' style='display:inline; font-size: 11px;'>" + numberWithCommas(thisMounth) +"원 </div>"
    	 				+ "<div class='tui-chart-tooltip-value'"+s_style+">" + "&nbsp;(" + numberWithCommas(Math.abs(thisMounth - preMounth)) + upDownTxt + ")"
    	 				+ "</div>";
            /* return wrap+head+body+"</div>"; */
    		return wrap+head+body+"</div>";
        }
    }

다른 영역도 가능할 까요?

**Comment by jinwoo-kim-nhn** [comment]
@GangHyeok-Ji 
Since the x and y axis are svg area, will not change the shape itself, like the `tooltip.template` option
But, you can use custom formatting option. Please refer to below link.

- https://github.com/nhnent/tui.chart/blob/production/docs/wiki/features-chart.md#custom-formatting

Or more options related to axis.
- https://github.com/nhnent/tui.chart/blob/production/docs/wiki/features-axes.md
