### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'browser' of undefined   에러가 발생합니다.

### ISSUE THREAD

**Issue by arsenal1779** [nhnent/tui.chart#130]
html 의 헤드 부분에 다음과 같이 코드를 추가하고 웹페이지를 실행하는데 자꾸 에러가 발생합니다.

<link rel="stylesheet" href="https://uicdn.toast.com/tui.chart/latest/tui-chart.min.css">
<script src="https://uicdn.toast.com/tui.chart/latest/tui-chart.min.js"></script>
<script src="https://unpkg.com/tui-code-snippet@1.4.0/dist/tui-code-snippet.js"></script>
<script src="/public/JS/raphael.js"></script>

에러 내용은 다음과 같습니다.

Uncaught TypeError: Cannot read property 'browser' of undefined    
at Object.<anonymous> (tui-chart.min.js:10)   
at e (tui-chart.min.js:10)    
at Object.<anonymous> (tui-chart.min.js:10)    
at e (tui-chart.min.js:10)   

그리고 웹페이지에서 차트를 이벤트를 통해 생성하면 또 에러가 발생합니다.

Uncaught (in promise) TypeError: Cannot read property 'barChart' of undefined   

이벤트 함수는 다음과 같습니다.

function RealTimeToastChart(elementId){

	chartElementObj = document.getElementById(elementId);
	
	this.name = elementId +"_object" ;

	var container = document.getElementById(chartElementObj);
	var data = {
			categories : ['cate1', 'cate2', 'cate3'	],
			series: [
	            {
	                name: 'Legend1',
	                data: [20, 30, 50]
	            },
	            {
	                name: 'Legend2',
	                data: [40, 40, 60]
	            },
	            {
	                name: 'Legend3',
	                data: [60, 50, 10]
	            },
	            {
	                name: 'Legend4',
	                data: [80, 10, 70]
	            }
	        ]
	}
	var options = {
		
		chart: {width: 700, height: 400, title: 'Chart Title'},
		xAxis: {title: 'Y Axis Title'},
		yAxis: {title: 'X Axis Title'}
	};
	tui.chart.barChart(container, data, options);
}

에러가 왜 발생하는지 해결방안 조언 부탁드립니다

**Comment by jinwoo-kim-nhn** [comment]
hello, @arsenal1779 
Please load `tui-code-snippet.js` first.
`tui-chart.js` has a module that depends on` tui-code-snippet.js`.
