### ISSUE TITLE
아직 모바일 지원은 안되나요?

### ISSUE THREAD

**Issue by bongjinpark1** [nhnent/tui.chart#131]
차트를 생성할때 적용한 가로세로 길이가, 작은 화면에서도 동일하게 보여지는것 같은데, 모바일 화면을 지원하는 기능이 있나요?

**Comment by jinwoo-kim-nhn** [comment]
hello @bongjinpark1 
Please refer to the following link to the wiki guide.I hope this guide will help you.
- https://github.com/nhnent/tui.chart/blob/production/docs/wiki/features-chart.md#setting-dimension-of-the-chart
