### ISSUE TITLE
Question: Can the X-Axis labels be rotated?

### ISSUE THREAD

**Issue by Mashiane** [nhnent/tui.chart#132]
## Version

Current version

## Development Environment

Windows

## Current Behavior

Just a question?
```js
// Write example code
```

**Comment by jinwoo-kim-nhn** [comment]
hello @Mashiane 
* Please refer to the following link to the wiki guide. I hope this guide will help you.
  - [wiki guide](https://github.com/nhnent/tui.chart/blob/production/docs/wiki/features-axes.md#how-to-not-rotated-label-of-x-axis)
