### ISSUE TITLE
[help wanted]y축배열을 내림차순으로 바꿀 수 있을까요?

### ISSUE THREAD

**Issue by goldsilverwater** [nhnent/tui.chart#14]
y축배열을 내림차순으로 바꿔서 그래프를 표현 할 수 있나요?
있다면 방법을 알려주세요.

**Comment by junghwan-park** [comment]
안녕하세요.

아쉽게도 현재 y축, x축을 내림차순으로 표현해주는 기능은 지원되고 있지 않습니다.
