### ISSUE TITLE
차트 객체에 접근하고자 하는데 잘 되지 않습니다.

### ISSUE THREAD

**Issue by cofham** [nhnent/tui.chart#144]
## Version
tui-chart 3.4.0

## Development Environment
node js eclipse

## Current Behavior

현재 node js 에서 tui-chart 를 이용해 차트를 만들고 있습니다.

```js
function drawColumnChart(){
 	chartObj = new tui.chart.columnChart(container, data, options);
}
```

위와같이 chartObj 라는 차트 객체를 생성하였는데 , 
실시간으로 데이터를 추가하기 위해 차트 객체에 접근이 필요합니다.

addData라는 메소드를 찾아서
`chartObj.addData(){data1,data2}` 이렇게 적용해보았는데 잘되지않습니다.

생성된 객체에 접근하고 addData를 적용하려면 어떻게 해야하는지 부탁드립니다.

**Comment by jung-han** [comment]
안녕하세요 @cofham 님 .
현재 사용하고 계신 columnChart의 `addData` 메서드는 동적으로 데이터를 추가 시켜주고 있지 않습니다.
만약 칼럼차트가 동적으로 변하게 반영하려면 차트를 다시 렌더링 하는 방식으로 구현하셔야 할 것 같습니다. 
혹은 라인차트에서 제공되는 [Dynamically adding data](https://github.com/nhnent/tui.chart/blob/production/docs/wiki/chart-types-line,area.md#dynamically-adding-data)가이드를 참조해 보시면 좋을 것 같습니다.

아무런 동작을 하지 않는 메서드가 추가 되어 혼잡을 드린점 죄송하고 이후 개선하도록 하겠습니다.
