### ISSUE TITLE
크롬 브라우저에서 example 실행해보고 있는데요.

### ISSUE THREAD

**Issue by nunghyun** [nhnent/tui.chart#15]
Run it! 버튼을 눌러도 반응이 없는데요. 확인 부탁해요.

**Comment by junghwan-park** [comment]
어떤 페이지에서 어떤 코드를 실행했는지 알려주시겠어요?

현재 예제페이지에서 작성된 코드에 예외가 발생한경우 이전상태의 코드를 실행시켜주고 있습니다.

**Comment by gem874** [comment]
제 경우에는 codemirror 관련 라이브러리가 없어서 발생하여 별도로 다운로드 받은 후, 옮겨두었더니 실행이 되었습니다. (tui.chart/lib/codemirror 아래에 codemirror 다운로드한 파일 위치)
