### ISSUE TITLE
radialChart Resize error

### ISSUE THREAD

**Issue by ssh1990** [nhnent/tui.chart#152]
## Version

* @version 3.4.1

## Development Environment

Windows10 , Chrome

## Current Behavior

```js
// Write example code
```

**Comment by jung-han** [comment]
@ssh1990
Thanks for reporting the issue. I'll fix it as soon as possible.

**Comment by wronax** [comment]
I can confirm this bug. The only way to resize radial chart is to render new chart what is not so elegant.

**Comment by jung-han** [comment]
Thanks. It will be fixed v3.6.0.
