### ISSUE TITLE
Resize fail on null data

### ISSUE THREAD

**Issue by yeongtaik** [nhnent/tui.chart#16]
안녕하세요. 

버그가 있는 것 같아 글을 씁니다.
line 챠트에서  showDot 옵션을 사용하고 있고 categories에 해당하는 값을 null을 주어 표시는 하고 있지 않는 값이 있을 때(처음, 마지막을 null로 주었습니다.) resize 함수를 호출하면 item.endDot이 undefined라 item.endDot.dot에서
Unhandled rejection TypeError: Cannot read property 'dot' of undefined 에러가 발생합니다.

**Comment by junghwan-park** [comment]
안녕하세요~

이슈 내용을 통해 해당 버그 내용 확인 했습니다.
소중한 버그 제보 감사드리며, 해당 이슈는 버그가 해결 된 후 comment 달도록 하겠습니다.

**Comment by jinwoo-kim-nhn** [comment]
this issue is resolved
