### ISSUE TITLE
Resized map chart overflows

### ISSUE THREAD

**Issue by dambusm** [nhnent/tui.chart#163]
## Version
3.4.2

## Development Environment
OSX, Chrome

## Current Behavior
Using the map chart, if I use the resize method, then zoom in to the resized map, the map overflows over other elements, seemingly to the original size.

Here's a demo: https://jsfiddle.net/cmhdwabx/
Just zoom in to the map and see it overflow over the adjacent elements.
![screenshot 2019-01-08 at 10 22 30](https://user-images.githubusercontent.com/12501819/50821393-5dd2d680-132f-11e9-8690-ec6cd6d755bb.png)

## Expected Behavior
Zoomed in maps should crop to the size they are resized to

**Comment by jung-han** [comment]
It will be fixed v3.6.0.
