### ISSUE TITLE
setData method throws TypeError on map chart

### ISSUE THREAD

**Issue by dambusm** [nhnent/tui.chart#164]
## Version
3.4.2

## Development Environment
OSX, Chrome

## Current Behavior
When I use the .setData method on a map chart, data fails to be set and an unhandled exception occurs:
```
Uncaught TypeError: dataProcessor.getZoomedRawData is not a function
    at MapChart.protectedRerender (VM83 tui-chart.js:16050)
    at MapChart.setData (VM83 tui-chart.js:16114)
    at (index):785
```
Demo here: https://jsfiddle.net/vL8tsbjx/1/

I've also tried on the bar chart, and setData appears to work fine there.

## Expected Behavior
.setData call should not throw an error

**Comment by jung-han** [comment]
It Fixed in v3.6.1.
