### ISSUE TITLE
[issue] map chart resize

### ISSUE THREAD

**Issue by gem874** [nhnent/tui.chart#17]
안녕하세요. 
아래의 사이트에서 chart 사용하는 것을 보고 여기까지 오게되었네요 
https://analytics.toast.com/analysis/leaveUser?appCode=p0HaZlgr&from=20170618&to=20170718

깔끔하고 제가 원하는 기능이 모두 들어가 있어서 해당 차트를 알게되어 사용을 하려고 하다보니, 
다른 chart는 resize가 제대로 적용되는데 map chart의 경우에는 오류가 발생하여 문의를 드리게 되었습니다. 

그리고 브라우저 창을 최대화, 최소화 하거나 할 때 
chart의 resize 기능이 제대로 동작되지 않습니다. 그래서 변경이 될 때 (resize) 페이지를 새로 고치게 하였는데 좋은 방법은 아닌 것 같아서.. 

바쁘시겠지만, 해당 부분들에 대해서 피드백 주시면 정말 감사하겠습니다.

**Comment by junghwan-park** [comment]
안녕하세요~
먼저 저희 TOAST UI Chart에 관심을 가져 주셔서 감사합니다.

말씀해주신 map chart의 resize 버그는 에러가 나는 부분을 확인했습니다. 수정이 반영되면 댓글로 알려드리겠습니다.

그 다음으로 문의 주신 Chart의 resize기능이 최대화, 최소화시 제대로 동작되지 않는다는 이슈를 확인해 보았습니다.
먼저 크롬, IE 11의 최대화, 복원 동작에서는 재현이 되지 않고있습니다. 창 사이즈(body의 onresize에 이벤트 핸들러를 바인딩 했습니다)에 맞게 즉각 반영됩니다. 여전히 리사이징이 원활하지 않다면 현재 사용하시는 차트의 버전과 `chart.resize()`를 적용하신 코드를 알려주시면 다시 한번 확인 하겠습니다.

제가 적용한 차트 resize 코드는 아래와 같습니다.
`tui.chart - 2.9.0`
링크 : https://nhnent.github.io/tui.chart/latest/tutorial-sample03-01-line-chart.html

``` js
// ... container, data, option defined here
// ...

var chart = tui.chart.lineChart(container, data, options);

document.body.onresize = function() {
    chart.resize({
        width: document.body.clientWidth/3,
        height: document.body.clientHeight/3
	});
};
```

**Comment by gem874** [comment]
안녕하세요 ^^ 이제서야 확인을 했네요!
보내주신 메일 잘 받았습니다.
해당 부분에 대해서 확인하고 수정해보도록 하겠습니다.
정말 좋은 chart를 공유해주셔서 잘 사용하고 있습니다.
그럼 좋은 하루되세요 감사합니다.

2017년 7월 24일 오후 5:52, 박정환 <notifications@github.com>님이 작성:

**Comment by jinwoo-kim-nhn** [comment]
this issue is resolved

**Comment by kimsinkyo** [comment]
안녕하세요 toast ui 차트부분을 사용하다 궁금해서 질문드립니다.
tui-chart.js 파일과 tui-chart-all.js 파일이 어떤점이 다른지 알고 싶습니다. 
알려주시면 감사드리겠습니다.

**Comment by jung-han** [comment]
@kimsinkyo 

Check this document.
* https://github.com/nhn/tui.chart#via-contents-delivery-network-cdn
