### ISSUE TITLE
map chart에서..

### ISSUE THREAD

**Issue by SHINMJ** [nhnent/tui.chart#18]
map chart 에서 tooltip을 항상 떠있게 할 수 있나요??
아니면 showLabel=true일 때 label을 커스터마이징 할 수 있나요??? tooltip 처럼 html 태그를 사용해서요.

**Comment by junghwan-park** [comment]
안녕하세요.

저희 차트에는 툴팁이 항상 열려있도록 제공하는 API는 없습니다.
툴팁이 항상 보이도록 하는 옵션 지원은 지원 방법 검토 후 추후 개선 목록에 추가하도록 하겠습니다.

series의 label은 현재 커스터마이징을 지원하지 않습니다.
그리고 label이 tooltip과는 다른 방식으로 그려지므로 tooltip과 동일하게 html태그를 이용해서 커스터마이징할 수 없는 구조입니다.

감사합니다.
