### ISSUE TITLE
API/Examples 메인 페이지가 작동 하지 않습니다.

### ISSUE THREAD

**Issue by SSocrates** [nhnent/tui.chart#186]
http://nhnent.github.io/tui.chart/latest/
해당 페이지에서 좌측 메뉴 [ Examples ] 및 API 검색 버튼을 클릭해도, 반응 하지 않습니다.

http://nhnent.github.io/tui.chart/latest/tutorial-example01-01-bar-chart-basic
예제 페이지에서 우측 레이아웃 [Result] [JavaScript] [HTML] 버튼 클릭시, 동작 하지 않습니다.

**Comment by jung-han** [comment]
@SSocrates Thanks for issue. I'll check it out ASAP.

**Comment by jung-han** [comment]
@SSocrates it's now fixed. Thanks.😁

**Comment by SSocrates** [comment]
> @SSocrates it's now fixed. Thanks.
