### ISSUE TITLE
Using tow y Axes in a combo chart

### ISSUE THREAD

**Issue by jaeyeolkim** [nhnent/tui.chart#19]
안녕하세요.
https://github.com/nhnent/tui.chart/wiki/chart-types-column-line-combo 
경로를 참조하여 **How to use two yAxis** 처리를 하려 하는데

example 사이트(https://nhnent.github.io/tui.chart/latest/tutorial-sample08-01-column-line-combo-chart.html) 에서 yAxis 선언부를 가이드대로 변경했는데 **우측 yAxis 가 나타나지 않습니다**.

[변경한 부분]
    yAxis: [{
        title: 'Temperature',
        chartType: 'column'
    }, {
        title: 'Average',
        chartType: 'line'
    }]

**Comment by junghwan-park** [comment]
안녕하세요~

보고해주신 우측 yAxis가 나타나지 않는 문제는 현재 버그 확인 및 해결중에 있습니다.
해당 버그가 해결되면 댓글을 남기고 이 이슈는 닫도록 하겠습니다.

소중한 제보 감사합니다. :)

**Comment by jinwoo-kim-nhn** [comment]
this issue is resolved
