### ISSUE TITLE
offset option for axis title does not work

### ISSUE THREAD

**Issue by cimfalab** [nhnent/tui.chart#20]
I'm using the latest 2.9.4.
When I set the axis option like the following, offset does not apply.
xAxis: {
        title: {
            text: 'X Axis Title',
            offsetX: 50,
            offsetY: 10
        }
    },

By seeing the function '_renderTitleArea', I think it's not implemeted.
Is it right?
Please review it :)

**Comment by youjung-hong** [comment]
Hello @cimfalab 
First of all, sorry for late response. I was on a holiday, and back in today.

As you mentioned above, `offsetX`, `offsetY` options are not yet implemented.
The option is implemented on to `title`  and `tooltip` option, not `xAxis`.

If you have any problems or request, please feel free to comment. Thank you.

**Comment by cimfalab** [comment]
Thank you for confirming.
I was confused by this tutorial: https://github.com/nhnent/tui.chart/wiki/features-axes#title-positioning
It will be better the tutorial is revised until the implementation :)

**Comment by youjung-hong** [comment]
I am very sorry for the confusion. 😭
I will check the diff and revise the tutorial. 

When this issue is resolved, I will mention you.
Thank you for contribution x 100!
