### ISSUE TITLE
README.md의 Download/Install 항목 링크 URI가 잘못되어 있네요.

### ISSUE THREAD

**Issue by venzersiz** [nhnent/tui.chart#22]
404 에러가 발생합니다.

**Comment by youjung-hong** [comment]
@venzersiz 제보 감사합니다.
메인 브랜치를 `master`에서 `production`으로 변경했는데 해당 내용이 반영되지 않았네요.

다운로드 링크는 다음과 같습니다.
https://github.com/nhnent/tui.chart/tree/production/dist

또한 README.md 파일 업데이트 후 댓글로 안내드리겠습니다.
행복한 연말 되셔요 ^.^

**Comment by venzersiz** [comment]
네 회사에서 사용할 예정인데, 둘러 보면서 오류가 나오면 이슈에 올려두겠습니다. 감사합니다.
