### ISSUE TITLE
barChar에서 카테고리 데이터 문의드려요

### ISSUE THREAD

**Issue by byunghweeLee** [nhnent/tui.chart#23]
혹시 카테고리나 데이터같은경우 배열 그 자체로 넣을수 있나요?
예를들어 
var container = document.getElementById('chart');
				var data = {
				  categories: [title],
				  series: [{
				    name: '남자',
				    data: [data1]
				  },{
				    name: '여자',
				    data: [data2]
				  }]
				};
위와같은경우 title, data1, data2가 배열자체인 상태인데 위와같이 하면 화면이 다 깨지는데 어찌 사용하는게 좋을까요?

**Comment by byunghweeLee** [comment]
아...
var container = document.getElementById('chart');
var data = {
categories: title,
series: [{
name: '남자',
data: data1
},{
name: '여자',
data: data2
}]
};
이렇게하니깐 되네요 ..

**Comment by youjung-hong** [comment]
해결하셨다니 다행이네요.
**categories**와 **data** 프로퍼티는 숫자 배열로 관리하고 있습니다.

차트 만드는 데 참고하실 수 있는 링크 공유드립니다.
아래 링크에 방문하시면, 차트를 만드는 데 필요한 데모와 예제 소스를 볼 수 있습니다.
https://nhnent.github.io/tui.chart/latest/index.html

혹시 더 궁금하신 사항 있으시면 댓글 남겨주세요.
Toast Chart에 대한 관심 감사합니다.

따뜻한 연말 되시길 바라요.^^
