### ISSUE TITLE
dot에 hover했을 때의 fillColor가 계속 유지됩니다.

### ISSUE THREAD

**Issue by godori** [nhnent/tui.chart#24]
안녕하세요 
tui.chart 2.9.0 이후 버전으로 업데이트 하였더니 다음과 같은 이슈가 있어 문의드립니다.
업데이트 한 버전은 2.12.1이고 demo페이지에서도 발생하는 것을 보니 최신 릴리즈도 동일한 것 같습니다.

line chart의 theme 설정에서 hover되었을 때 dot 스타일이 변경되도록 하였는데요, 
마우스를 off한 상태에서 기존 dot으로 돌아오지 않습니다.
```var theme = {
    series: {
        colors: ['#111'],
        dot: {
            fillColor: null,
            fillOpacity: 1,
            radius: 5,
            strokeColor: '#fff',
            strokeOpacity: 1,
            strokeWidth: 2,
            hover: {
                fillColor: '#ffe100',
                fillOpacity: 1,
                radius: 7,
                strokeColor: '#111',
                strokeOpacity: 1,
                strokeWidth: 3
            }
        }
    }
};
```

dot의 fillColor를 null이 아닌 다른 값으로 바꾸어도 동일합니다. hover하지 않았을 때 다시 원래의 dot이 되었으면 하는데 혹시 테마 적용 방법이 바뀌었는지 이슈인지 모르겠어서 문의드립니다. (관련 document는 바뀌지 않은 듯 합니다 ㅠㅠ)
![image](https://user-images.githubusercontent.com/8243284/34813204-608c0726-f6ec-11e7-8457-ac70dbd984a2.png)

**Comment by youjung-hong** [comment]
안녕하세요~
문의 주신 내용 2.9.3 버전 이후 발생하는 버그👿로 확인하였습니다.
해당 이슈 수정 후에 댓글드리겠습니다.

소중한 제보 감사드리며, 차트 이용에 불편을 드려 죄송합니다.
정말 고맙습니다.🤗

**Comment by youjung-hong** [comment]
안녕하세요~ 해당 버그 v2.14.2 버전에서 수정되었습니다.
차트 이용 감사합니다!

**Comment by youjung-hong** [comment]
안녕하세요
