### ISSUE TITLE
position line(dot) to center if x axis has one tick

### ISSUE THREAD

**Issue by youjung-hong** [nhnent/tui.chart#29]
## Version

v2.14.2

## Current Behavior

![screenshot-2018-01-31 11 29 31 773](https://user-images.githubusercontent.com/13758710/35602732-4663d57c-067d-11e8-9c3b-42de55336c21.png)

## Expected Behavior

![2018-01-31 12 54 01](https://user-images.githubusercontent.com/13758710/35604585-374d63b0-0686-11e8-8141-26ab2dd62c44.png)

**Comment by youjung-hong** [comment]
@venzersiz

Thank you for your report on the TOAST UI chart. 
I will mention it again when this problem is solved. 🤗

**Comment by jung-han** [comment]
@venzersiz 
Sorry for late.
It has been fixed after 3.0.0 version.
