### ISSUE TITLE
Invalid value for <rect> attribute y="NaN", 

### ISSUE THREAD

**Issue by miss0110** [nhnent/tui.chart#3]
If data field of series in json format has the same values, it causes the following exception
```
Exception : Invalid value for <rect> attribute y='NaN'
```
Please refer to the attached file for details
[tui_bug.tar.gz](https://github.com/nhnent/tui.chart/files/53384/tui_bug.tar.gz)

**Comment by extremeFE** [comment]
차트 이용에 감사드립니다.

최대, 최소값이 같은 경우가 정상적으로 처리되지 않아 발생한 문제입니다.
해당 부분에 대한 테스트 코드를 강화하였으며, 다음 배포에 반영 될 예정입니다.

감사합니다.

**Comment by extremeFE** [comment]
금일 배포된 1.4.0버전에서 해당 내용이 반영 되었습니다.

감사합니다.
