### ISSUE TITLE
Axis tick label alignment, when label is rotated

### ISSUE THREAD

**Issue by youjung-hong** [nhnent/tui.chart#31]
## Version

v2.14.2

## Development Environment

Chrome, OSX

## Current Behavior

Axis tick alignment is weired when label is rotated.
![x](https://user-images.githubusercontent.com/13758710/35664305-d296585c-0764-11e8-98a4-a84a338466d0.png)
![x](https://user-images.githubusercontent.com/13758710/35664312-d65f9a34-0764-11e8-9e7f-8ac6b7302c77.png)

## Expected Behavior

![bae2484a-e3e9-11e7-9302-8ae604f5e350](https://user-images.githubusercontent.com/13758710/35664445-7350f5f4-0765-11e8-9e8a-71a5aec7d12c.png)

**Comment by youjung-hong** [comment]
Report from @venzersiz

**Comment by jinwoo-kim-nhn** [comment]
this issue is resolved
