### ISSUE TITLE
New options to set text of `Zoom Reset` button

### ISSUE THREAD

**Issue by youjung-hong** [nhnent/tui.chart#32]
## Version

v2.14.2

## Development Environment

Chrome, OSX

## Current Behavior

Cannot change text of `Reset Zoom` button
![2018-02-01 7 40 24](https://user-images.githubusercontent.com/13758710/35674362-c4ad1fe6-0787-11e8-848e-cffcc3c00834.png)

## Expected Behavior

Can change text of `Reset Zoom` button

**Comment by youjung-hong** [comment]
Report from @venzersiz

**Comment by jung-han** [comment]
@venzersiz
Sorry for late.
It has been fixed after 3.0.0 version.
