### ISSUE TITLE
ie8에서 chartExportMenu가 안보입니다

### ISSUE THREAD

**Issue by zeussim** [nhnent/tui.chart#34]
ie8에서 bar차트를 사용 중입니다. *^^*
크롬에서는 export 메뉴가 보이는데요(정상동작)
ie8에서는 export 메뉴가 안보입니다

tui-chart.css 코드를 보니~ .tui-chart-chartExportMenu-area 에 z-index:5000; 으로 
되어있더군요~ 이문제는 아닌것 같은데요~

ie8은 export 기능을 지원안하는것인가요?

**Comment by youjung-hong** [comment]
Hey! @zeussim 
Thank you for your feedback on TOAST UI Chart.

You're right. The exporting menu is not supported on IE9 and less versions.
There are two options for downloading: download via `<a>`, or via `Blob`
`<a>.download` is not support IE.
`window.Blob`, `window.navigator.msSaveOrOpenBlobs` is supported IE10+.

I hope it helped to resolve your questions.

**Comment by zeussim** [comment]
감사합니다~
