### ISSUE TITLE
New option for not to show axis labels, only show axis line

### ISSUE THREAD

**Issue by youjung-hong** [nhnent/tui.chart#36]
## Version

v2.16.0

## Development Environment

Chrome, OSX

## Current Behavior

When rendering axis area, it renders axis lines and axis labels.
Need an option for not to show axis labels.

![2018-02-19 18-41-03 843](https://user-images.githubusercontent.com/13758710/36371421-62c7c57a-15a5-11e8-8ce1-c5526542e340.png)

## Expected Behavior

![2018-02-19 18-41-22 471](https://user-images.githubusercontent.com/13758710/36371428-67bd0126-15a5-11e8-8876-f6eb52e18e0b.png)

**Comment by youjung-hong** [comment]
Hey, @kind102 
Thank you for your report on TOAST UI Chart.🙌🏻
I will mention again when this issue is resolved.

We loves issue reporting 💖.
If you have questions or find🔦 some bugs, report us.📡
Thank you✨

**Comment by youjung-hong** [comment]
Looks good to me!

**Comment by jinwoo-kim-nhn** [comment]
this issue is resolved
