### ISSUE TITLE
Loading chart data from a file

### ISSUE THREAD

**Issue by djkeh** [nhnent/tui.chart#4]
Hi,
It seems Toast UI chart currently has no option to read data from files such as csv, xml, or json.
As far as I know there's a couple of open source javascript chart libraries which support file loading features through simple forms of methods and parameters.

Here's one of what I've found below:

[http://c3js.org/samples/data_url.html](http://c3js.org/samples/data_url.html)

I think this is pretty good idea, especially for those who are not programmers, and even for programmers this works pretty fine as it's simple, easy to understand the code, and reduces some meaningful amount of time.

How do you think about supporting this feature?

**Comment by extremeFE** [comment]
좋은 의견 감사드립니다.

말씀하신 부분과 유사한 기능은 개발 계획에 포함되어있습니다.

2016년 6월 정도 개발 예정이며, ajax(jsonp)방식으로 지원할 예정입니다.

감사합니다.

참고로, 이슈등록 시 한글로 적어주셔도 됩니다. ^^

**Comment by djkeh** [comment]
csv는 꼭 추가되었으면 좋겠습니다. 엑셀 파일을 변환해서 편리하게 사용할 수 있을 것 같습니다.
비개발자가 사용하기 더 좋을 것 같아요.

**Comment by extremeFE** [comment]
csv파일에 대해서도 고려해보겠습니다.
의견 감사드립니다.
