### ISSUE TITLE
error install on yarn 1.5.1

### ISSUE THREAD

**Issue by Gemorroj** [nhnent/tui.chart#40]
see https://github.com/yarnpkg/yarn/issues/5417

**Comment by kyuwoo-choi** [comment]
issue reported on https://github.com/nhnent/tui.editor/issues/96

**Comment by jinwoo-kim-nhn** [comment]
Fixed sources for yarn installation errors will be released next Tuesday.

As a temporary workaround, modify the raphael version of the last line of package.json to use it immediately.

```javascript
  "dependencies": {
    "raphael": "https://github.com/nhnent/raphael.git#2.2.0-c",
    "tui-code-snippet": "^1.2.5"
  }
```

**Comment by jinwoo-kim-nhn** [comment]
It is changed.
