### ISSUE TITLE
 Tooltips are not reordered after a series is selected in the legend area

### ISSUE THREAD

**Issue by youjung-hong** [nhnent/tui.chart#44]
## Current Behavior

```js
// Write example code
```

## Expected Behavior

When, a series is selected in the legend area, the serie pops to front.
If a series is 4th series, it would showed on the top of other series.

However, when hover on this poped series, tooltip showed the first series.
This means that, although series order was reordered, tooltip order is not.
Tooltip should be reordered too.

**Comment by youjung-hong** [comment]
duplicated #35

**Comment by jinwoo-kim-nhn** [comment]
resolved
