### ISSUE TITLE
custom-event-area is not overlayed on svg chart area

### ISSUE THREAD

**Issue by dioscuroi** [nhnent/tui.chart#47]
## Development Environment
React, Chrome

## Current Behavior
First of all, thanks a lot for providing such an awesome library!

I have an issue that the custom-event-area is not put on top of the svg chart area. As shown in the image below, both the export-menu and event-area div's are all placed below the chart.

<img width="1401" alt="screen shot 2018-03-07 at 10 26 18 am" src="https://user-images.githubusercontent.com/20280642/37064689-1520d7ae-21f2-11e8-9925-a2f255b706e4.png">

I tried the absolute position but with no luck.
```
<div id="chart-area" style={{position: 'absolute'}} />
```

Did I miss anything? Below is the full code that I tested.
```
import React, { Component } from 'react';
import TuiChart from 'tui-chart';

class TestTuiChart extends Component {
  componentDidMount() {
    var container = document.getElementById('chart-area');
    var data = {
        categories: ['01/01/2016', '02/01/2016', '03/01/2016', '04/01/2016', '05/01/2016', '06/01/2016', '07/01/2016', '08/01/2016', '09/01/2016', '10/01/2016', '11/01/2016', '12/01/2016'],
        series: [
            {
                name: 'Seoul',
                data: [-3.5, -1.1, 4.0, 11.3, 17.5, 21.5, 24.9, 25.2, 20.4, 13.9, 6.6, -0.6]
            },
            ......
        ]
    };
    var options = {
        chart: {
            width: 700,
            height: 400,
            title: '24-hr Average Temperature'
        },
        ......
    };
    
    TuiChart.lineChart(container, data, options);
  }  

  render() {
    return (
      <div id="chart-area" style={{position: 'absolute'}}>
      </div>
    )
  }
}

export default TestTuiChart;

```

**Comment by jinwoo-kim-nhn** [comment]
Sorry for the delay.
css does not seem to apply.
When tui-chart.css is not applied, the following phenomenon may occur.
Please check and have a good day.

**Comment by doowb** [comment]
I had the same issue and it was fixed by including the css.

**Comment by shinjayne** [comment]
Can someone tell me how to include tui css in react component ?

**Comment by meetzaveri** [comment]
@shinjayne Include it directly in index.html
