### ISSUE TITLE
CDN?

### ISSUE THREAD

**Issue by suntong** [nhnent/tui.chart#55]
From

https://github.com/nhnent/tui.chart/blob/production/docs/wiki/getting-started.md

> The downloaded file will be saved in "bower_components" directory. . . If you included files, now you can create a chart. 

So, would you put your latest code into [CDN](https://en.wikipedia.org/wiki/Content_delivery_network) please? so that people can try them out without even installing anything. Thx!

**Comment by jinwoo-kim-nhn** [comment]
Thank you for your feedback. I'll try it out.

**Comment by jinwoo-kim-nhn** [comment]
You can now use the cdn.

- You can use cdn as below.

```html
<link rel="stylesheet" href="https://uicdn.toast.com/tui.chart/latest/tui-chart.min.css">
<script src="https://uicdn.toast.com/tui.chart/latest/tui-chart.min.js"></script>
```

- Within the download you'll find the following directories

```
tui.chart/
├─ latest
│  ├─ tui-chart.js
│  ├─ tui-chart.min.js
│  ├─ tui-chart.css
│  ├─ tui-chart.min.css
│  ├─ maps/
│  │  ├── (china | japan | singapore | south-korea | taiwan | thailand | use | world).js
├─ v3.0.1/
```
