### ISSUE TITLE
line chart 몇 가지 문의

### ISSUE THREAD

**Issue by Drdoteam** [nhnent/tui.chart#6]
안녕하세요.
클라우드플랫폼개발팀 신진호 입니다.

line chart에서 몇 가지 궁금한게 있어서 문의 드립니다.

1. 가운데 정렬?
만약 값이 하나 만 있을 경우, 차트 왼쪽 구석에 위치하게 되는데 이 때 가운데 위치하게 할 수 있나요?

2. series 색 변경
Defaul 색인 빨강, 주황 외 다른 색으로 변경하고 싶은데, 어떻게 설정해야되는지 궁금합니다.

3. 왼쪽, 오른쪽 padding?
값들을 넣으면 양 끝의 값들은 양 끝 쪽에 위치하게 되는데, 이 때 약간 여유 공간을 설정할 수 있나요?

답변 부탁드립니다.

**Comment by junghwan-park** [comment]
1. 해당 경우의 가운데 정렬 기능은 지원하지 않습니다. lineChart는 데이터가 2개이상이어야 line이 정상적으로 그려지게 됩니다.

2. series색 변경은 https://github.com/nhnent/tui.chart/wiki/theme 를 참고하시기 바랍니다.

3. line차트 series영역의 padding을 말씀하시는건가요? 만약 그렇다면 현재 지원하지 않습니다.
category가 있는 lineChart의 경우 axis영역에 닿도록 렌더링이 되고있습니다.

**Comment by Drdoteam** [comment]
@junghwan-park 답변 감사합니다!
