### ISSUE TITLE
Getting Started내 예제에서 문제점 발견했습니다.

### ISSUE THREAD

**Issue by paulsoh** [nhnent/tui.chart#7]
안녕하세요.

우선 이렇게 좋은 오픈소스 활동을 해주시는 데에 있어서 존경과 감사의 말씀을 드립니다.

https://github.com/nhnent/tui.chart/wiki/getting-started#create-chart
에 있는 예제에서 조금 이상한 부분을 발견했습니다.
예제의 데이터를 그대로 사용을 하고, barChart를 렌더링을 하면 다음과 같은 경우에 

![image](https://cloud.githubusercontent.com/assets/18063110/23660359/82976e9a-038c-11e7-93d1-11e24c682b89.png)

Legend1 에 대해서 첫번 째 bar가 렌더링이 되지 않는 것을 볼 수 있습니다.

Data 값을 바꿔봤더니 또 제대로 렌더링이 되더라구요..
![image](https://cloud.githubusercontent.com/assets/18063110/23660429/c422c4cc-038c-11e7-9253-f1cee65d1bed.png)

혹시 예제의 데이터로 했을 때 값이 안 나오는 이유가 있을까요?

**Comment by junghwan-park** [comment]
안녕하세요~

먼저 말씀해주신 첫번째 이미지 cate1의 bar가 렌더링 되지 않은 이유는 `xAxis`의 min값과 cate1의 데이터 값이 같아서 입니다.

현재 axis에 min, max 옵션이 없을 경우 최소, 최대 값에 맞게 차트를 보여주게 되는데요,
만약 데이터들이 위의 차트와 동일할때 xAxis를 0부터 표현하려면 axis옵션을 다음과 같이 설정하면 됩니다.

``` javascript
var options = {
    xAxis: {
        min: 0,
        max: 50
    }
};
```
다음 링크를 참고하시면 axis의 더 많은 옵션들을 확인할 수 있습니다. [https://github.com/nhnent/tui.chart/wiki/features-axes#setting-min-max](https://github.com/nhnent/tui.chart/wiki/features-axes#setting-min-max)

**Comment by paulsoh** [comment]
답변 감사합니다!
