### ISSUE TITLE
self.moveDot is not a function

### ISSUE THREAD

**Issue by me3602** [nhnent/tui.chart#70]
## Version

3.0.1
## Development Environment

Window, Chrome, nodejs
## Current Behavior

```js
snippet.forEachArray(self.groupDots[groupIndex], function(item, index) {
	if (item.endDot) {
		self.moveDot(item.endDot.dot, groupPositions[groupIndex][index]);
	}
});
```

## Expected Behavior

 안녕하세요. 우선 좋은 차트라이브러를 개발해주셔서 감사드립니다.
차트 구현 중 resize 함수를 사용하게 되었는데요 위와 같은 에러가 발생하여 확인을 해보았습니다.
위 구문에서 self.moveDot 가 self._moveDot(언더바 추가)의 오타가 아닌가 하여 제보 드립니다.

**Comment by jinwoo-kim-nhn** [comment]
네 안녕하세요 me3602님 제보 감사드립니다. 해당 부분 수정중에 있으며 4월 중에 배포될 예정입니다.
감사합니다.

**Comment by jinwoo-kim-nhn** [comment]
this issue is resolved
