### ISSUE TITLE
In ES6 node.js, import {chart} does not work 

### ISSUE THREAD

**Issue by shinjayne** [nhnent/tui.chart#77]
## Version

tui-chart 3.0.1

## Development Environment

node.js, webpack

## Current Behavior

If I import like below (just as the documentation described), I only get `undefined`. 
```js
import { chart } from 'tui-chart'

console.log( chart );
// undefined
```

But if I import like this, It works! Just as expected.
```js
import  myChart  from 'tui-chart'

console.log( myChart );
// {barChart: ƒ, columnChart: ƒ, lineChart: ƒ, areaChart: ƒ, bubbleChart: ƒ, …}
```
I think something is wrong ...

Could someone explain about this thing ? 

## Expected Behavior

Expected Behavior (described in documentation) is like below.
```js
import  {chart}  from 'tui-chart'

console.log( chart );
// {barChart: ƒ, columnChart: ƒ, lineChart: ƒ, areaChart: ƒ, bubbleChart: ƒ, …}
```

**Comment by jinwoo-kim-nhn** [comment]
Thank you shinjayne, I now know about this.
I will solve this soon.

**Comment by jinwoo-kim-nhn** [comment]
Sorry shinjayne, currently only one basic export is supported and provided, so it looks correct to write like this:
~~~javascript
import  myChart  from 'tui-chart'
~~~
Corrected incorrect information about "named import" in the guide.

**Comment by shinjayne** [comment]
Oh thanks. It really helps :-)
