### ISSUE TITLE
Bubble Chart : 데이터가 하나만 있을 경우, 값이 중복될 경우

### ISSUE THREAD

**Issue by goohooh** [nhnent/tui.chart#8]
```javascript
rawData = {
  series: [
    {
      name: 'test',
      data: [
        // {x: 400, y:200, r:1, label:'T*T'},
        // {x: 600, y:400, r:1, label:'T*T'},
        {x: 600, y:300, r:1, label:'T*T'}
      ]
    }
  ]
};
```
이런식으로 데이터를 하나만 입력할 경우
제대로 렌더링이 되질 않습니다.
차트에 마우스를 올려 툴팁을 보면 x,y 각각의 값이 null로 표시 됩니다.
범위를 잡지 못한 탓인지 xAxis, yAxis도 표기되지 않습니다.
그리고

```javascript
rawData = {
  series: [
    {
      name: 'test',
      data: [
        // {x: 400, y:200, r:1, label:'T*T'},
        {x: 600, y:400, r:1, label:'T*T'},
        {x: 600, y:300, r:1, label:'T*T'}
      ]
    }
  ]
};
```
데이터가 2개 이상이라도 x혹은 y값이 같을 때,
위처럼 x값이 동일한경우 x값만 null로 표기 됩니다.(xAxis만 표기 안됨)

이를 해결할 방법이 없을까요?
덧붙여 이처럼 좋은 프로젝트를 오픈소스로 제공해주셔서 정말 감사합니다.

**Comment by junghwan-park** [comment]
안녕하세요 ~

말씀해주신 차트의 데이터만으로는 정확히 재현이 되지 않습니다.
사용하신 TUI Chart의 버전과 차트 옵션까지 알려주시면 확인해 드리겠습니다.

말씀해주신 case들은 2.8.2 버전에서 일부 처리가 되었는데요, yAxis, xAxis 옵션에 **각각 min, max값이 있는 경우**에 한해 툴팁 데이터의 렌더링만 정상동작 되고 있었습니다. 
하지만 axis의 min, max를 계산하는 부분에서 동일 데이터에대한 처리가 없어서 렌더링이 되지 않는 경우가 발생되는게 확인되었습니다.
이 이슈는 해결된 버전이 배포되면 같이 닫도록 하겠습니다.

이상동작, 버그 제보에 감사드립니다. :)

**Comment by goohooh** [comment]
빠른 답변 감사합니다!
