### ISSUE TITLE
Add marker to line chart, highlight area in chart  

### ISSUE THREAD

**Issue by YuqinShi1226** [nhnent/tui.chart#89]
## Version
v 3.1.0

## Development Environment
Chrome 

## Current Behavior
Not able to add maker to a certain point in line chart, or highlight certain area in chart 

## Expected Behavior
I attached 2 pictures of expected behavior
1. Able to mark points in line chart
2. Able to highlight line a range of data in line chart
![images](https://user-images.githubusercontent.com/11971026/39222924-e3a07c9c-4871-11e8-9e8f-4963fc67d57d.png)
![download](https://user-images.githubusercontent.com/11971026/39222925-e467bc8a-4871-11e8-8daa-2cacab22ed0f.png)

**Comment by jinwoo-kim-nhn** [comment]
Perhaps, the corresponding option on our chart would be helpful to you.

1. `series.showDot` of line chart ([more detail](https://github.com/nhnent/tui.chart/blob/master/docs/wiki/features-series.md#showing-dot-on-series-area))
    series: {
        showDot: true
    },

~~~javascript
var options = {
    ...
    series: {
        showDot: true
    }
};
~~~

2. `plot.lines` or `plot.bands` option for highlight line ([more detail](https://github.com/nhnent/tui.chart/blob/master/docs/wiki/features-plot.md#how-to-setting-plot-line-and-band))

~~~javascript
var options = {
    ...
    plot: {
        lines: [{
            value: '03/01/2016',
            color: '#ff5a46'
        }]
    }
};
~~~
|       |       |
| --- | --- |
|![2018-04-26 11 13 33](https://user-images.githubusercontent.com/35218826/39282456-6c9d1762-4944-11e8-91a7-fe5e159465b0.png)| ![2018-04-26 11 15 14](https://user-images.githubusercontent.com/35218826/39282506-999c16c8-4944-11e8-97f6-e3bce82e368b.png) |
