### ISSUE TITLE
Customize display of axes and background lines

### ISSUE THREAD

**Issue by MihajloVeljanovski** [nhnent/tui.chart#90]
Hello,

Suppose I have a chart like this:

![image](https://user-images.githubusercontent.com/9343195/39297423-c3c14654-4943-11e8-8471-fee836c83f0a.png)

Is it possible to remove(not display) the y axis and the grayed lines that constitute the background of the chart?

Many thanks.

**Comment by jinwoo-kim-nhn** [comment]
hello @MihajloVeljanovski
* The `plot.hideLine` option will help.

~~~javascript
//...
var options = {
    plot: {
        hideLine: true
    }
};
tui.chart.barChart(container, data, options);
~~~

* There is no option to hide the y axis yet.
