### ISSUE TITLE
안녕하세요. toast ui chart (bulletChart) resize 에러가 있어서 문의드립니다.

### ISSUE THREAD

**Issue by dreamcombo** [nhnent/tui.chart#98]
안녕하세요. 
chart 개발을 하고 있는 초보 개발자입니다. 

bulletchart 사용하여 차트를 만들고 있는데 resize 차트모양이 변하는 현상이 있어서 문의 드립니다.

처음 로딩을 했을때 모습
![1](https://user-images.githubusercontent.com/39080594/39915516-1dcbc498-5543-11e8-91ce-3daa2bbce0d3.PNG)

웹브라우저 크기를 변경했을때 모습
![2](https://user-images.githubusercontent.com/39080594/39915592-4d3861aa-5543-11e8-897f-ebd79d74447a.PNG)

제가 사용법이 미숙해서 그런지는 모르겠지만 혹시 이유를 알 수있을까요?

현재 작성한 코드 입니다.
function chart2_Load() {
		var w;
		var h;
	
		w = $('#chart2').parent('div').width() - 2;
		h = $('#chart2').parent('div').height() - 
                $('#grid1').parent('div').find('div.grid_top_wrap').outerHeight(true); 
	
		var container = document.getElementById('chart2');
		var data = {
		    categories: ['test', 'test1'],
		    series: [{
		        name: '가방',
		        data: 1000,
		        markers: [],
		        ranges: []
		    }, {
		        name: '원피스',
		        data: 2000,
		        markers: [],
		        ranges: []
		    }, {
		        name: '바지',
		        data: 4000,
		        markers: [],
		        ranges: []
		    }, {
		        name: '모자',
		        data: 5000,
		        markers: [],
		        ranges: []
		    }, {
		        name: '신발',
		        data: 5000,
		        markers: [],
		        ranges: []
		    }]
		};
		var options = {
		    chart: {
		        width: w,
		        height: h,
		        format: '1,000',
		        title: 'test1',
		    },
		    legend: {
		        visible: true
		    },
		    series: {
		        showLabel: true,
		        vertical: false
		    }
		};

		var chart2=tui.chart.bulletChart(container, data, options);
		
		$(window).bind('resize', function(e) {
			 chart2.resize({
		        width: $('#chart2').parent('div').width()-2,
		        height: 
  $('#chart2').parent('div').height()-$('#grid1').parent('div').find('div.grid_top_wrap').outerHeight(true)
			}); 
		});
}

**Comment by jinwoo-kim-nhn** [comment]
Hi, @dreamcombo. 

This is a bug in bulletChart.
This bug fix will be included in the next month's release.

**Comment by dreamcombo** [comment]
감사합니다.

**Comment by dreamcombo** [comment]
혹시 pie chart도 resize 버그가 있는건가요??

function chart11_Load() {
	var w;
	var h;

	w = $('#chart11').parent('div').width()-2;
	h = $('#chart11').parent('div').height()-5;

	var container = document.getElementById('chart11');
	var data = {
				    categories: ['품목'],
				    series: 
				    [
				        {
				            name: "원피스",
				            data: 25
				        },
				        {
				        	name: "청바지",
				            data: 25
				        },
				        {
				        	name: "반팔티",
				            data: 25
				        },
				        {
				        	name: "셔츠",
				            data: 25
				        }
				    ] 
				};
		var options = {
		    chart: {
		        width: w,
		        height: h,
		        title: '의류 분포도',
		        format: function(value, chartType, areaType, valuetype, legendName) {
		            if (areaType === 'makingSeriesLabel') { // formatting at series area
		                value = value + '%';
		            } 
		            return value;
		        }
		    },
		    series: {
		        radiusRange: ['40%', '100%'],
		        showLabel: true
		    },
		    tooltip: {
		        suffix: '%'
		    },
		    legend: {
		        visible: false
		    }
		};
		var theme = {
		    series: {
		        series: {
		            colors: [
		                '#83b14e', '#458a3f', '#295ba0', '#2a4175', '#289399',
		                '#289399', '#617178', '#8a9a9a', '#516f7d', '#dddddd'
		            ]
		        },
		        label: {
		            color: '#fff',
		            fontFamily: 'sans-serif'
		        }
		    }
		};

	    var chart11 = tui.chart.pieChart(container, data, options);
	
 		$(window).bind('resize', function(e) {
		    chart11.resize({
		        width: $('#chart11').parent('div').width()-2,
		        height: $('#chart11').parent('div').height()-5
			});
		}); 
} 

이상태로 웹페이지 사이즈를 줄이면
Cannot read property 'x' of undefined
이라는 오류메세지가 뜨는데.... 차트마다 resize하는 방식이 다 다른건가요??

**Comment by jinwoo-kim-nhn** [comment]
sorry @dreamcombo 
Each chart has a different drawing method, and you can see the symptoms on the pie chart as well. We will improve this part.

**Comment by jinwoo-kim-nhn** [comment]
this issue is resolved
